export type LLMModel = {
  id: string;
  name: string;
  inputModalities?: string[];
  outputModalities?: string[];
};

export type LLMProvider = {
  slug: string;
  name: string;
  models: LLMModel[];
};

// Deepgram STT supported languages
export const deepgramSTTSupportedLanguages = [
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Finnish",
  "Flemish",
  "French",
  "German",
  "Greek",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Marathi",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];

// Cartesia STT supported languages
export const cartesiaSTTSupportedLanguages = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Faroese",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Norwegian Nynorsk",
  "Occitan",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Sanskrit",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Turkish",
  "Turkmen",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "Yiddish",
  "Yoruba",
  "Yue Chinese",
];

// Smallest AI STT supported languages
export const smallestAiSTTSupportedLanguages = [
  "Bengali",
  "Bulgarian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Finnish",
  "French",
  "German",
  "Gujarati",
  "Hindi",
  "Hungarian",
  "Italian",
  "Kannada",
  "Latvian",
  "Lithuanian",
  "Malayalam",
  "Maltese",
  "Marathi",
  "Oriya",
  "Polish",
  "Portuguese",
  // "Punjabi",
  "Romanian",
  "Russian",
  "Slovak",
  "Spanish",
  "Swedish",
  "Tamil",
  "Telugu",
  "Ukrainian",
];

// Google STT supported languages
export const googleSTTSupportedLanguages = [
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Bengali",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Lao",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Odia",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Sepedi",
  "Serbian",
  "Sindhi",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Xhosa",
  "Zulu",
];

// ElevenLabs STT supported languages
export const elevenlabsSTTSupportedLanguages = [
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Asturian",
  "Azerbaijani",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Bulgarian",
  "Burmese",
  "Cantonese",
  "Catalan",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Hausa",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maltese",
  "Mandarin",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Northern Sotho",
  "Norwegian",
  "Occitan",
  "Odia",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Shona",
  "Sindhi",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tajik",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "Wolof",
  "Xhosa",
  "Yoruba",
  "Zulu",
];

// Sarvam STT supported languages (Indic language specialist)
export const sarvamSTTSupportedLanguages = [
  "Bengali",
  "English",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Maithili",
  "Malayalam",
  "Marathi",
  "Odia",
  "Punjabi",
  "Tamil",
  "Telugu",
];

// Groq STT supported languages (Whisper on Groq)
export const groqSTTSupportedLanguages = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Cantonese",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Faroese",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maori",
  "Marathi",
  "Mongolian",
  "Myanmar",
  "Nepali",
  "Norwegian",
  "Nynorsk",
  "Occitan",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Sanskrit",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Turkish",
  "Turkmen",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "Yiddish",
  "Yoruba",
];

// Groq TTS supported languages (Orpheus)
export const groqTTSSupportedLanguages = [
  "English",
];

// Cartesia TTS supported languages
export const cartesiaTTSSupportedLanguages = [
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Finnish",
  "French",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Malayalam",
  "Marathi",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Slovak",
  "Spanish",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];

// Google TTS supported languages
export const googleTTSSupportedLanguages = [
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Malayalam",
  "Marathi",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Sindhi",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
];

// ElevenLabs TTS supported languages
export const elevenlabsTTSSupportedLanguages = [
  "Arabic",
  "Bulgarian",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malay",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Sindhi",
  "Slovak",
  "Spanish",
  "Swedish",
  "Tamil",
  "Turkish",
  "Ukrainian",
];

// OpenAI STT supported languages
export const openaiSTTSupportedLanguages = [
  "Afrikaans",
  "Arabic",
  "Armenian",
  "Azerbaijani",
  "Belarusian",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Finnish",
  "French",
  "Galician",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Marathi",
  "Maori",
  "Nepali",
  "Norwegian",
  "Persian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Welsh",
];

export type STTProvider = {
  label: string;
  value: string;
  model: string;
  website: string;
  supportedLanguages?: string[];
  modelOverrides?: Record<string, string>;
};

export type TTSProvider = {
  label: string;
  value: string;
  model: string;
  voiceId: string;
  website: string;
  supportedLanguages?: string[];
  modelOverrides?: Record<string, string>;
};

export const sttProviders: STTProvider[] = [
  { label: "Deepgram", value: "deepgram", model: "nova-3", website: "https://deepgram.com", supportedLanguages: deepgramSTTSupportedLanguages },
  { label: "OpenAI", value: "openai", model: "gpt-4o-transcribe", website: "https://openai.com", supportedLanguages: openaiSTTSupportedLanguages },
  { label: "Cartesia", value: "cartesia", model: "ink", website: "https://cartesia.ai", supportedLanguages: cartesiaSTTSupportedLanguages },
  { label: "ElevenLabs", value: "elevenlabs", model: "scribe-v2", website: "https://elevenlabs.io", supportedLanguages: elevenlabsSTTSupportedLanguages },
  { label: "Groq", value: "groq", model: "whisper-large-v3-turbo", website: "https://groq.com", supportedLanguages: groqSTTSupportedLanguages },
  { label: "Google", value: "google", model: "chirp-3", website: "https://cloud.google.com/speech-to-text", supportedLanguages: googleSTTSupportedLanguages, modelOverrides: { "Sindhi": "chirp-2" } },
  { label: "Sarvam", value: "sarvam", model: "saarika-v3", website: "https://sarvam.ai", supportedLanguages: sarvamSTTSupportedLanguages },
  { label: "Smallest AI", value: "smallest", model: "pulse", website: "https://smallest.ai", supportedLanguages: smallestAiSTTSupportedLanguages },
];

/*
┌─────────────┬──────────────────────────┐
│ Label       │ Model                    │
├─────────────┼──────────────────────────┤
│ Deepgram    │ nova-3                   │
│ OpenAI      │ gpt-4o-transcribe        │
│ Cartesia    │ ink                      │
│ ElevenLabs  │ scribe-v2                │
│ Groq        │ whisper-large-v3-turbo   │
│ Google      │ chirp-3                  │
│ Sarvam      │ saarika-v3               │
│ Smallest    │ pulse                    │
└─────────────┴──────────────────────────┘
*/

export const ttsProviders: TTSProvider[] = [
  { label: "Cartesia", value: "cartesia", model: "sonic-3.5", voiceId: "Riya", website: "https://cartesia.ai", supportedLanguages: cartesiaTTSSupportedLanguages },
  { label: "OpenAI", value: "openai", model: "gpt-4o-mini-tts", voiceId: "coral", website: "https://openai.com", supportedLanguages: openaiSTTSupportedLanguages },
  { label: "Groq", value: "groq", model: "orpheus", voiceId: "troy", website: "https://groq.com", supportedLanguages: groqTTSSupportedLanguages },
  { label: "Google", value: "google", model: "chirp_3", voiceId: "Charon", website: "https://cloud.google.com/text-to-speech", supportedLanguages: googleTTSSupportedLanguages, modelOverrides: { "Sindhi": "gemini" } },
  { label: "ElevenLabs", value: "elevenlabs", model: "eleven_multilingual_v2", voiceId: "Krishna", website: "https://elevenlabs.io", supportedLanguages: elevenlabsTTSSupportedLanguages, modelOverrides: { "Sindhi": "eleven_v3" } },
  { label: "Sarvam", value: "sarvam", model: "bulbul:v3", voiceId: "aditya", website: "https://sarvam.ai", supportedLanguages: sarvamSTTSupportedLanguages },
  { label: "Smallest AI", value: "smallest", model: "lightning-v3.1", voiceId: "aditi", website: "https://smallest.ai", supportedLanguages: smallestAiSTTSupportedLanguages },
];

/*
┌─────────────┬──────────────────────────┬──────────────────────────────────────────┐
│ Label       │ Model                    │ Voice ID                                 │
├─────────────┼──────────────────────────┼──────────────────────────────────────────┤
│ Cartesia    │ sonic-2                  │ 638efaaa-4d0c-442e-b701-3fae16aad012     │
│ OpenAI      │ gpt-4o-mini-tts          │ coral                                    │
│ Groq        │ playai-tts               │ Arista-PlayAI                            │
│ Google      │ chirp-3                  │ Aoede                                    │
│ ElevenLabs  │ eleven_multilingual_v2   │ IbEzPPGLXlYUvxNGhJQp                     │
│ Sarvam      │ bulbul:v3                │ aditya                                    │
│ Smallest    │ lightning-v3.1           │ emily                                    │
└─────────────┴──────────────────────────┴──────────────────────────────────────────┘
*/
